name: Build and Test Live Treasury Yield Curve Analyzer

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [Release, Debug]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup C++ environment
      uses: aminya/setup-cpp@v1
      with:
        compiler: gcc
        cmake: true
        make: true

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=CMakeLists_LIVE.txt

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} --target yield_analyzer_live

    - name: Test
      working-directory: build
      run: ctest -C ${{ matrix.build_type }}

    - name: Upload artifacts
      if: matrix.os == 'ubuntu-latest' && matrix.build_type == 'Release'
      uses: actions/upload-artifact@v4
      with:
        name: yield-analyzer-live-linux
        path: build/yield_analyzer_live
